---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  - name: ubuntu-12.10
    driver_config:
      box: opscode-ubuntu-12.10
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.10_provisionerless.box
  - name: ubuntu-13.04
    driver_config:
      box: opscode-ubuntu-13.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[varnishd::default]
    attributes:
